keys:
  - &admin_tchikmagalore age1nfk7a5w92ywtwyl8grtf7nj9evas7am29saw6xeejz7hqm6pwcsqr0htms
creation_rules:
  - filename_regex: \.secrets\.yaml$
    key_groups:
    - age:
      - *admin_tchikmagalore